Topic/bugfix/memo1.0 003
ITPMAndroid/android-ojt-memo-app pull request #3
Opened 2020-01-11 06:51 UTC by koya-hikigi

2020-01-11 07:07 UTC, GanhoKoh reviewed
マージ先がmasterとなっています。正しいburnchesに変更をお願いいたします。

2020-01-11 07:29 UTC, syou-kou requested changes
ソースの設定は正しいのですが、コメントが正しくありません。
（コメントの色設定は元々正しかったのですが、入れ替えてしまったため）
修正のほど、よろしくお願いいたします。

2020-01-18 10:09 UTC, koya-hikigi commented
@syou-kou さん
コメントの修正を行いました。
確認をお願い致します。

2020-01-18 10:16 UTC, syou-kou approved these changes
確認いたしました。
問題ないと思います。

2020-01-18 10:37 UTC, itpm-sakamoto approved these changes
確認しました。
問題ないと思います。

2020-01-18 10:37 UTC, merged