[MEMO1.0-008]: ゴミ箱が空の場合の表示が正しくない。修正
ITPMAndroid/android-ojt-memo-app pull request #8
Opened 2020-01-18 09:22 UTC by koya-hikigi

### **問題の原因**

- メモがない状況でゴミ箱を選択した場合でも
「空です」と表示されていた。

### **対応内容**

- MainFragmentにて条件分岐を行い
　メモがない状況ゴミ箱を選択した場合、
　「ゴミ箱にメモがありません」と表示されるよう変更

### **fixed file**

- MainFragment

### **コミット前の動作確認**

- 実行前の状態：メモを空にしておく。
- アプリを起動する。
- ナビゲーションメニューから「ゴミ箱」を選択。
- 画面中央に「ゴミ箱にメモがありません」と表示される。

2020-01-18 10:05 UTC, GanhoKoh requested changes
リソースファイルにある文言を利用した方が良いかと思われます。
string.xml内に該当のものがあるのでそれを利用する修正を頂きたく思います。
    <string name="not_memo">メモがありません。</string>
    <string name="not_delete_memo">ゴミ箱にメモがありません。</string>

2020-01-18 10:26 UTC, koya-hikigi commented
@GanhoKoh さん
ご指摘ただいた内容にて修正を行いました。
確認をお願い致します。

2020-01-25 04:25 UTC, itpm-sakamoto approved these changes
確認しました。
問題ないと思います。

2020-01-25 04:29 UTC, itpm-sakamoto commented
コンフリクトを起こしているので解消してほしいです。

2020-01-25 04:48 UTC, GanhoKoh approved these changes
問題ないことを確認いたしました。

2020-01-25 04:48 UTC, itpm-sakamoto approved these changes
問題ないです。

2020-01-25 04:48 UTC, merged